version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: always
    volumes: 
      - ./docker-data/db-data:/var/lib/mysql
    environment:
      COMPOSE_PROJECT_NAME: ${PROJECT_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306  

  adminer:
    depends_on: 
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080